Update tasks.yml

diff --git a/.tekton/tasks.yml b/.tekton/tasks.yml
--- a/.tekton/tasks.yml
+++ b/.tekton/tasks.yml
@@ -1,3 +1,4 @@
+# 1 Create cleanup Tekton task
 ---
 apiVersion: tekton.dev/v1beta1
 kind: Task
@@ -33,3 +34,29 @@ spec:
       # Delete files and directories starting with .. plus any other character
       rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
     fi
+
+    # 2 Create test Tekton task
+
+    ---
+apiVersion: tekton.dev/v1beta1
+kind: Task
+metadata:
+  name: nose
+spec:
+  workspaces:
+    - name: source
+  params:
+    - name: args
+      description: Arguments to pass to nose
+      type: string
+      default: "-v"
+  steps:
+    - name: nosetests
+      image: python:3.9-slim
+      workingDir: $(workspaces.source.path)
+      script: |
+          #!/bin/bash
+  set -e
+  python -m pip install --upgrade pip wheel
+  pip install -r requirements.txt
+  nosetests $(params.args)
